### ISSUE TITLE
tsm cleanup -v

### ISSUE THREAD

**Issue by Sivivatu** [til-jmac/tableau-server-housekeeping#10]
the -v switch in the tsm maintenance cleanup call appears to be removed.

**Comment by markusG90** [comment]
This is changing the cleanup command and does not require tsm password or username anymore

[housekeeping.zip](https://github.com/til-jmac/tableau-server-housekeeping/files/4182346/housekeeping.zip)

**Comment by Sivivatu** [comment]
@markusG90 I'm not sure what you are saying. Yes it is modifying the clean-up (because the -v switch has been removed). The tsm username/password was not part of this update and is a future project requirement
