### ISSUE TITLE
Error in backup script

### ISSUE THREAD

**Issue by dtackley** [til-jmac/tableau-server-housekeeping#12]
In /tableau-server-housekeeping/windows/2019.2 and later/tableau-server-backup-script.cmd you look to have removed the command line options for tsm username and password. There is however still one occurrence in the script that is looking for these and this is causing the script to error and partially fail:

_:: Grab the location of the backup directory
:set_backup_dir
ECHO %date% %time% : Getting the location of the default backup directory
FOR /F "tokens=* USEBACKQ" %%F IN (`tsm configuration get -k basefilepath.backuprestore -u %tsmadmin% -p %tsmpassword%`) DO (SET "backuppath=%%F")
ECHO The default backup path is: 
ECHO %backuppath%_

If you remove the _-u %tsmadmin% -p %tsmpassword%_ from the script all then works correctly.

**Comment by til-jmac** [comment]
Fixed
