### ISSUE TITLE
Suggestion ..

### ISSUE THREAD

**Issue by israelsilvaBR** [til-jmac/tableau-server-housekeeping#3]
Hi. Great job. Thanks.
I implemented it for my Tableau Server maintenance routine.

Suggestion: Cleanup section in the beginning of the script. Tableau recommends to clean up logs and temporary files before backing up to keep data files size smaller. Backup runs faster.

There are some minor errors I have corrected in my version:
1 - In the tsm maintenance backup command, the $backupname should be $backup_name.
2 - There is missing "echo" word command in the else statements when "found, deleting..." (both else statements).

Thanks for sharing.

**Comment by LanesG** [comment]
It would be great if you could also fix error 2.
Thank you for the script!
